2021-01-31 19:01:48,263 - python_app - DEBUG - Random demo app started
2021-01-31 19:01:48,484 - python_app - DEBUG - Random demo app started
2021-01-31 19:03:10,004 - python_app - DEBUG - Random demo app started
2021-01-31 19:03:10,217 - python_app - DEBUG - Random demo app started
2021-01-31 19:04:11,058 - python_app - DEBUG - Random demo app started
2021-01-31 19:06:43,742 - python_app - DEBUG - Random demo app started
2021-01-31 19:06:43,949 - python_app - DEBUG - Random demo app started
2021-01-31 19:12:37,999 - python_app - DEBUG - Random demo app started
2021-01-31 19:12:38,203 - python_app - DEBUG - Random demo app started
2021-01-31 19:58:31,479 - python_app - DEBUG - MQTT App started
2021-01-31 19:58:46,800 - python_app - DEBUG - MQTT App started
2021-01-31 22:08:23,694 - python_app - DEBUG - MQTT App started
2021-01-31 22:24:12,124 - python_app - DEBUG - MQTT App started
2021-01-31 22:25:11,955 - python_app - DEBUG - MQTT App started
2021-01-31 22:25:16,675 - python_app - ERROR - Erro writing to grafana <paho.mqtt.client.MQTTMessage object at 0x7fe018051eb0>, error: HTTPConnectionPool(host='influxdb', port=8086): Max retries exceeded with url: /write?db=influx (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe01656e610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
